### PR TITLE
determinant function

### LINKED ISSUE #30: Determinant of NXN matrix
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Dterminant is very useful for many matrix operations and a function for this will hence be very handy

### PR DESCRIPTION
**Pull request by sreechand2002**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #30 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
determinant function

### CODE REVIEW

**Review by shreya1010svg — COMMENTED** [review]
Hey can you please explain the algorithm, like add some documentation. It's a rather big function so I'd like it to be like easily understandable to other contributors too.

**Comment by sreechand2002** [comment]
so i should i add a text file describing about the function

**Comment by shreya1010svg** [comment]
That's fine or you could update the readme. Anything.

**Comment by sreechand2002** [comment]
done

**Comment by shreya1010svg** [comment]
!bounty 50

**Pull request merged**
