### PR TITLE
Pr for isIdentity

### PR DESCRIPTION
**Pull request by sreechand2002**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
Create a Pr for isIdentity as i had included this in last PR but to count for bounty i am creating a PR

### CODE REVIEW

**Comment by sakshi2912** [comment]
@sreechand2002 Could you please provide a brief summary of why you made the PR, it looks like you haven't filled the PR template.

**Comment by sreechand2002** [comment]
i had solved this issue in my last PR itself along with another issue but since for bounty points , i created this PR

**Comment by Rishabkashyap14** [comment]
Yeah this I have reviewed with your multiplication PR if I am not wrong

**Comment by sakshi2912** [comment]
> i had solved this issue in my last PR itself along with another issue but since for bounty points , i created this PR

Alright!

**Comment by sreechand2002** [comment]
can you merge this PR soon, so that i can open a new PR

**Comment by Rishabkashyap14** [comment]
Hey buddy @sreechand2002 could you give us the screenshots of your executions for confirmation before merging?

**Review by shreya1010svg — COMMENTED** [review]
Does it work for the case like:
1 0 0 0
0 2 0 0
0 0 1 0
0 0 0 1
If possible send a screenshot

**Comment by shreya1010svg** [comment]
Not all of them just this one, I think there should be a small change. Not sure

**Comment by shreya1010svg** [comment]
I'm sorry that we're taking so long, this just caught me is all

**Comment by sreechand2002** [comment]
i have resolved the error now you may check it out

**Comment by shreya1010svg** [comment]
!bounty 10

**Comment by shreya1010svg** [comment]
!bounty 10

**Pull request merged**
