### PR TITLE
Added the function LUdecomposition

### PR DESCRIPTION
**Pull request by anushka-gupta-31**
# Pull Request Template

## Description

 This function decomposes the matrix into lower triangular and upper triangular matrices.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I have run the code in compiler

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by shreya1010svg — COMMENTED** [review]
Okay so you're returning only the lower matrix, can you return both upper and lower matrices as an array of objects or something? And because this is a relatively large algorithm can you add some documentation on the algorithm used and the code corresponding to it so that it is easier for other contributors to understand the code.

**Comment by anushka-gupta-31** [comment]
@shreya1010svg  Ya sure I'll do it.

**Comment by anushka-gupta-31** [comment]
Please review the changes I have made in this pull request #47

**Comment by Rishabkashyap14** [comment]
!bounty 50

**Comment by anushka-gupta-31** [comment]
I have also added the documentation for this function in this pull request #48

**Pull request merged**
