### PR TITLE
cofactor function

### LINKED ISSUE #55: cofactor function
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
cofactor is required to find inverse , adjoint matrix and in many other operation , so have it as a function rather write the code again and again is better

### PR DESCRIPTION
**Pull request by sreechand2002**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #55 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
cofactor function added

### CODE REVIEW

**Review by shreya1010svg — COMMENTED** [review]
Correct me if I am wrong, doesn't cofactor mean (-1)^(i+j)*(determinant of the submatrix)?
If I am not wrong you have given the submatrix required only.

**Comment by sreechand2002** [comment]
you are correct , when this submatrix is passed to the determinant function then we will get the cofactor right

**Comment by shreya1010svg** [comment]
So you haven't calculated or called determinant in this right? You could add that

**Comment by sreechand2002** [comment]
i have called cofactor, which is giving out the submatrix inside determinant , which in turn is used to calculate determinant , there by optimising the determinant function also

**Comment by shreya1010svg** [comment]
I think it's the other way round mathematically but since you have gotten the determinant optimized and the cofactor correction is very minor I'll take this

**Comment by shreya1010svg** [comment]
!bounty 40

**Pull request merged**
