### PR TITLE
matrix multiplication

### PR DESCRIPTION
**Pull request by sreechand2002**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
Matrix multiplication

### CODE REVIEW

**Comment by Rishabkashyap14** [comment]
Hey @sreechand2002  amazing job on the PRs but you will have to comment on the issue you wish to work on to create a PR for them as it helps us track your work. So keep this in mine and keep up the good work!

**Comment by sreechand2002** [comment]
sure , i will comment from on issues from now onwards

**Comment by Rishabkashyap14** [comment]
Thanks a lot buddy, have fun!

**Comment by shreya1010svg** [comment]
!bounty 30

**Comment by shreya1010svg** [comment]
!bounty 30

**Pull request merged**
